spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  h2:
    console:
      enabled: true
      path: /h2

  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
#
#  jpa:
#    properties:
#      hibernate:
#        show_sql: true
#        format_sql: true
#
#logging:
#  level:
#    org:
#      hibernate:
#        type: trace